# Cask
cask_args appdir: "/Applications"
tap "caskroom/cask"

# Programming
cask "caskroom/versions/java8"
brew "gradle"
brew "leiningen"
brew "node"
brew "nvm"
brew "rbenv"
brew "ruby-build"

# Git
brew "git"
brew "git-crypt"
brew "git-plus"

# CLI
cask "iterm2"
brew "direnv"
brew "gnupg"
brew "jq"
brew "openssl"

#AWS
brew "awscli"
cask "aws-vault"

# Apps
cask "atom"
cask "docker"
cask "dropbox"
cask "google-chrome"
cask "intellij-idea"
cask "keepassxc"
cask "postman"
cask "slack"
cask "tunnelblick"
cask "zoomus"
